# Generated by Django 5.2.3 on 2025-07-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='process_status',
            field=models.CharField(choices=[('waiting_confirmation', 'Menunggu Konfirmasi Resto'), ('processing', 'Diproses'), ('ready_for_pickup', 'Siap Diambil'), ('delivering', 'Dikirim'), ('completed', 'Selesai')], default='waiting_confirmation', max_length=32),
        ),
    ]
