# Generated by Django 5.2.3 on 2025-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nusavorauser',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
