# Generated by Django 5.2.3 on 2025-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nusavorauser_username'),
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nusavorauser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='products.product'),
        ),
    ]
