# Generated by Django 5.2.1 on 2025-05-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vendor_recommendation_location_based_user_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='kabupaten_kota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
