# Generated by Django 5.2.3 on 2025-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
