# Generated by Django 5.2.3 on 2025-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
